SecAction \
    "id:10000,\
    phase:1,\
    pass,\
    nolog,\
    initcol:ip=%{REMOTE_ADDR}"

SecRule ARGS_NAMES "@streq password" \
    "id:10001,\
    phase:1,\
    chain,\
    pass,\
    nolog,\
    setvar:ip.dvwa_brute_count=+1,\
    expirevar:ip.dvwa_brute_count=60"
    SecRule REQUEST_URI "@rx (login\.php|brute)"

SecRule IP:DVWA_BRUTE_COUNT "@gt 5" \
    "id:10002,\
    phase:1,\
    deny,\
    status:403,\
    msg:'Brute Force Blocked (Count: %{IP.dvwa_brute_count})'"
