SecRule REQUEST_URI "@contains /vulnerabilities/csrf" \
    "id:10003,\
    phase:1,\
    chain,\
    deny,\
    status:403,\
    msg:'DVWA: CSRF Attempt Blocked'"

    SecRule QUERY_STRING "@contains password_new" \
        "chain"
        SecRule REQUEST_HEADERS:Referer "!@contains /vulnerabilities/csrf"

