SecRule ARGS_NAMES "@pm redirect url return next dest" \
  "id:1000001,\
  phase:2,\
  deny,\
  status:403,\
  t:lowercase,\
  chain"
  SecRule ARGS "@rx ^(https?://|//|.*\.(com|org|net|edu|io)(/|$))" \
    "msg:'Custom Rule: Open Redirect Attack Blocked'"
